#! /bin/sh


PADDING=20
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config split_ratio					0.51
bspc config window_gap          20
bspc config left_padding        "$PADDING"
bspc config right_padding       "$PADDING"
bspc config border_width 0
bspc config top_padding 56
bspc config bottom_padding 2

bspc config gapless_monocle     false 

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

PATH="$HOME/.config/bspwm/scripts:$PATH"


# Terminate already running polybar, stalonetray, sxhkd and dunst instances
processes=("sxhkd" "polybar" "dunst" "xfce4-clipman")

	for process in "${processes[@]}"; do
		if pgrep -f "$process"; then
			pkill -9 -f "$process" > /dev/null; sleep 0.1
		fi
	done


sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &
nitrogen --restore &
chmod +x scripts/* &
dunst -config "$HOME"/.config/bspwm/dunstrc &
pidof -q picom || { picom -b --config "$HOME"/.config/bspwm/picom.conf & }
pidof -q eww || { eww -c "$HOME"/.config/bspwm/eww daemon & }
polybar -q oasis -c $HOME/.config/bspwm/polybar/config.ini &
timedatectl set-ntp true &
xfce4-clipman &
xset r rate 200 2h &
